version: '3.8'
services:
  kali:
    build: kali/.
    stdin_open: true
    tty: true
    networks:
      - testbed
    volumes:
      - local_rules:/rules

  snort:
    depends_on:
      - kali
    build: snort/.
    network_mode: 'host'
    environment:
      NET_IF: br-a6138535ea2d
      SNORT_OUTMODE: alert_fast
    cap_add:
      - NET_ADMIN
    volumes:
      - local_rules:/rules:ro

  suricata:
    depends_on:
      - kali
    build: suricata/.
    network_mode: 'host'
    environment:
      NET_IF: br-a6138535ea2d
    cap_add:
      - NET_ADMIN
    volumes:
      - local_rules:/rules:ro

networks:
  testbed:
    external: true

volumes:
  local_rules:
